### PR TITLE
Visual Studio support

### LINKED ISSUE #2: Visual Studio support
@madebygps do you want Visual Studio support in your project? If you add a `solution` file and include all the three `projects` in it, then people can open that `solution` file in Visual Studio and work with this project.

If you want Visual Studio support, then can I send a pull request?

### PR DESCRIPTION
**Pull request by Arnab-Developer**
Created a Visual Studio `solution` file and added all the projects into it.

Fixes #2

### CODE REVIEW

**Comment by Arnab-Developer** [comment]
image

**Comment by Arnab-Developer** [comment]
This is ready for review.

**Comment by madebygps** [comment]
Thank you so much!!!!

**Comment by Arnab-Developer** [comment]
Thank you.

**Pull request merged**
